### ISSUE TITLE
Right banner can't close

### ISSUE THREAD

**Issue by Compound-codes** [python-nerd-3/crystal-coves#1]
The left banner can't close, so much of the screen isn't shown, could you add a js button that hides it and opens it when wanted?

**Comment by python-nerd-3** [comment]
Will do in next update. For now you can zoom out.

**Comment by python-nerd-3** [comment]
also its on the right,, joog gob

**Comment by python-nerd-3** [comment]
i accidentally closed

**Comment by Compound-codes** [comment]
I'm so smart
right = left

**Comment by python-nerd-3** [comment]
i fixed it for you bc you cant granmder
