### ISSUE TITLE
Kind of bad ui

### ISSUE THREAD

**Issue by Compound-codes** [python-nerd-3/crystal-coves#2]
why does the left banner have a horizontal scroll bar?
(p. s. don't have horizontal scroll bars unless absolutely necessary)

**Comment by python-nerd-3** [comment]
I can't fit like 20 ores into 1 sidebar without it being visually unappealing
Working on an update right now to add GUI buttons for save and clear mine

**Comment by Compound-codes** [comment]
P. S.
Just make the ores smaller 🦆

**Comment by python-nerd-3** [comment]
no then You Cant See The Deatils Or Counts 🦆🦆🦆 it would be tiny (you will se next updatyo)

**Comment by Compound-codes** [comment]
ok!
:D
Yey
😺
