### ISSUE TITLE
link color

### ISSUE THREAD

**Issue by Compound-codes** [python-nerd-3/crystal-coves#3]
![Screen Shot 2023-03-19 at 11 28 07](https://user-images.githubusercontent.com/68404606/226186456-6b823a28-73b2-401a-b640-f71829787801.png)

the link color is hard to read, change it to a light color or people might not see a link is there

**Comment by python-nerd-3** [comment]
Planned feature will do in this update

**Comment by python-nerd-3** [comment]
improved it
