### ISSUE TITLE
Credits favicon

### ISSUE THREAD

**Issue by Compound-codes** [python-nerd-3/crystal-coves#4]
it has none, like the known bugs,
---------------------------------------------
get an icon that everybody will remember, instead of just all the ores.
Get like a beautiful icon that is very memorable. 🌈 
---------------------------------------------------------------------
You could use it just for Credits and Known bugs, but I recommend it to be as all of the favicons. :P

**Comment by python-nerd-3** [comment]
I like the cycle feature it's a cool idea but I will give a static favicon to credits and bugs
