### ISSUE TITLE
How to contact?

### ISSUE THREAD

**Issue by Compound-codes** [python-nerd-3/crystal-coves#6]
Don't ask them to make a github account, just make them email you. or me.

Also add that at the bottom of your pages
use `<footer> `

This is much easier for them, for it is likely that they have an email.

Asking for a github account might make them a bit suspicious, and also, if they're just going to add to one project, but don't want to code anything else, don't make them make a github account

**Comment by python-nerd-3** [comment]
yadaba i dont care i think its fien everyone knows what github is that actually follow my prowjcrtes

**Comment by python-nerd-3** [comment]
the only way people will find this in the first place is github, its not like its being advertized ort smth

**Comment by python-nerd-3** [comment]
woops i accidentally reopened

**Comment by python-nerd-3** [comment]
close

**Comment by python-nerd-3** [comment]
CLOSE I SEAD

**Comment by Compound-codes** [comment]
what happened here!??!?!?
