### ISSUE TITLE
old-amethyst

### ISSUE THREAD

**Issue by Compound-codes** [python-nerd-3/crystal-coves#7]
don't keep old files, github has you covered!
seriously, you can go back to your older commits and just take stuff from there, instead of just keeping your old file as extra data

**Comment by python-nerd-3** [comment]
i don't know why i have them there its not like its tons of megabytes the textures take up ~500 bytes each and it's never referred to in the code so it doesn't need to send requests

**Comment by Compound-codes** [comment]
2 kilobytes so far
